### ISSUE TITLE
yea a better pyclibrary, but with the same issue :( enum not found...

### ISSUE THREAD

**Issue by gcmartijn** [MatthieuDartiailh/pyclibrary#16]
I'm trying to extract all the C headers to create a wrapper.
Things I need are the structs/enums/functions.

At the moment i'm trying that with this C lib: https://www.libsdl.org/download-2.0.php
Everything is looking good except for this header file.

SDL_video.h
typedef enum
{
    SDL_WINDOW_FULLSCREEN = 0x00000001,
    SDL_WINDOW_OPENGL = 0x00000002,
    SDL_WINDOW_SHOWN = 0x00000004,
    SDL_WINDOW_HIDDEN = 0x00000008,
    SDL_WINDOW_BORDERLESS = 0x00000010,
    SDL_WINDOW_RESIZABLE = 0x00000020,
    SDL_WINDOW_MINIMIZED = 0x00000040,
    SDL_WINDOW_MAXIMIZED = 0x00000080,
    SDL_WINDOW_INPUT_GRABBED = 0x00000100,
    SDL_WINDOW_INPUT_FOCUS = 0x00000200,
    SDL_WINDOW_MOUSE_FOCUS = 0x00000400,
    SDL_WINDOW_FULLSCREEN_DESKTOP = ( SDL_WINDOW_FULLSCREEN | 0x00001000 ),
    SDL_WINDOW_FOREIGN = 0x00000800,
    SDL_WINDOW_ALLOW_HIGHDPI = 0x00002000
} SDL_WindowFlags;

To know if it was found I do this:
import pyclibrary
header_files = []
for file in os.listdir('../Downloads/SDL2-2.0.3/include/'):
    if file.endswith(".h"):
        header_files.append('../Downloads/SDL2-2.0.3/include/' + file)
p = pyclibrary.CParser(files=header_files,cache=u'C2MX2.cachefile')
print p.defs 

then I do a quick search for the word: SDL_WINDOW_OPENGL
But it was not found :(

**Comment by MatthieuDartiailh** [comment]
It appear pyclibrary does not recognize typedef enum hence the missing value. I will try to fix it ASAP.

**Comment by MatthieuDartiailh** [comment]
Actually that is not the problem. The issue is that the following is not correctly handled : 
SDL_WINDOW_FULLSCREEN_DESKTOP = ( SDL_WINDOW_FULLSCREEN | 0x00001000 )

I will try to fix it.

**Comment by MatthieuDartiailh** [comment]
I just pushed a fix. Could you try latest master ?

**Comment by gcmartijn** [comment]
Nope, din't work yet.

**Comment by MatthieuDartiailh** [comment]
I am surprised on my side parsing only the SDL_video.h I do get the right values for the enumeration. However some functions might be missing because DECLSPEC need to be parsed before. I do not now the library nut I would suggest to try to parse first begin_code.h. 
If you still have issues with enum please post the output of : 
```python
p = pyclibrary.CParser(files=header_files, process_all=False)
print p.process_all(return_unparsed=True)
p.print_all()
```

**Comment by gcmartijn** [comment]
Thanks its working when I use process_all=False
I dunno why, but then its working.

Another thing that don't work at the moment is the cachefile
I try it like this:
p = pyclibrary.CParser(files=header_files, cache=u'C2MX2.cachefile', process_all=False)
p = pyclibrary.CParser(files=header_files, cache=unicode('C2MX2.cachefile'), process_all=False)

this did work with the other pyclibrary.

Ow btw
this is the output from p.process_all(return_unparsed=True)
Maybe you see something interesting for the future.

[u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\nstatic \n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\nstatic \nstatic \nstatic \nstatic \n', u'\nextern  int  SDL_SetError(const char *fmt, ...);\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\nextern  void  SDL_Log(const char *fmt, ...);\nextern  void  SDL_LogVerbose(int category, const char *fmt, ...);\nextern  void  SDL_LogDebug(int category, const char *fmt, ...);\nextern  void  SDL_LogInfo(int category, const char *fmt, ...);\nextern  void  SDL_LogWarn(int category, const char *fmt, ...);\nextern  void  SDL_LogError(int category, const char *fmt, ...);\nextern  void  SDL_LogCritical(int category, const char *fmt, ...);\nextern  void  SDL_LogMessage(int category,\n                                            SDL_LogPriority priority,\n                                            const char *fmt, ...);\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\nstatic \nstatic \n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\ntypedef int SDL_dummy_ ## uint8[(sizeof ( Uint8 ) == 1) * 2 - 1];\ntypedef int SDL_dummy_ ## sint8[(sizeof ( Sint8 ) == 1) * 2 - 1];\ntypedef int SDL_dummy_ ## uint16[(sizeof ( Uint16 ) == 2) * 2 - 1];\ntypedef int SDL_dummy_ ## sint16[(sizeof ( Sint16 ) == 2) * 2 - 1];\ntypedef int SDL_dummy_ ## uint32[(sizeof ( Uint32 ) == 4) * 2 - 1];\ntypedef int SDL_dummy_ ## sint32[(sizeof ( Sint32 ) == 4) * 2 - 1];\ntypedef int SDL_dummy_ ## uint64[(sizeof ( Uint64 ) == 8) * 2 - 1];\ntypedef int SDL_dummy_ ## sint64[(sizeof ( Sint64 ) == 8) * 2 - 1];\ntypedef int SDL_dummy_ ## enum[(sizeof ( SDL_DUMMY_ENUM ) == sizeof ( int )) * 2 - 1];\nstatic \nstatic \nextern  int  SDL_sscanf(const char *text, const char *fmt, ...);\nextern  int  SDL_snprintf(char *text, size_t maxlen, const char *fmt, ...);\n', u'\n', u'\n', u'\nstruct SDL_SysWMmsg\n{\n    union\n    {\n        struct\n        {\n        } \n        struct\n        {\n        } \n    } \n};\n', u'\n', u'\nvoid SDLTest_Assert(int assertCondition, const char *assertDescription, ...);\nint SDLTest_AssertCheck(int assertCondition, const char *assertDescription, ...);\nvoid SDLTest_AssertPass(const char *assertDescription, ...);\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\nvoid SDLTest_Log(const char *fmt, ...);\nvoid SDLTest_LogError(const char *fmt, ...);\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n', u'\n']

**Comment by MatthieuDartiailh** [comment]
I will try to look into the issue you encountered. Thanks for the report.

**Comment by MatthieuDartiailh** [comment]
I guess that it was not working at first because I forgot to increase the parser version and hence the values were loaded from the cache. Could you delete the cache file and check ?

What do you mean by the cache does not work for this : 
p = pyclibrary.CParser(files=header_files, cache=u'C2MX2.cachefile', process_all=False)
This does not parse the headers so no cache is generated. If you then call p.process_all the cache should be generated.

**Comment by gcmartijn** [comment]
I deleted the cachefile then run the same script
p = pyclibrary.CParser(files=header_files, cache=unicode('C2MX2.cachefile'), process_all=False)
p.process_all(return_unparsed=True)
and when everything was done, there was no cache file inside the script directory.

but that is not a big deal for now, its only very time consuming ;)
maybe I have to use a /full/root/path now, din't check that.
