### ISSUE TITLE
Update package on PyPi

### ISSUE THREAD

**Issue by aagallag** [MatthieuDartiailh/pyclibrary#31]
The version of [pyclibrary](https://pypi.org/project/pyclibrary/) on PyPi seems to be `0.1.3`, however, the latest release on Github is `0.1.4`.

**Comment by MatthieuDartiailh** [comment]
I will try to update the package this week. Thanks for noticing.

**Comment by MatthieuDartiailh** [comment]
Sorry I am running late here but I am very busy this week so it may be another week of delay. Sorry

**Comment by aagallag** [comment]
Thanks for following up!

**Comment by MatthieuDartiailh** [comment]
Done
