### ISSUE TITLE
Bitfield not always recognized/parsed

### ISSUE THREAD

**Issue by nefhal** [MatthieuDartiailh/pyclibrary#41]
Hello,

I will give an example to present the problem:

typedef struct {
      int a   :   MY_BITFIELD;
} my struct;

If MY_BITFIELD defintion is not defined inside the same file with the "my_struct" definition, then pyclibrary fails to parse the definition.

Is this a known problem? Is it going to be resolved ?

Thank you in advance,
Nefeli

**Comment by MatthieuDartiailh** [comment]
Could you share how you call pyclibrary ? In particular, do you pass both headers to pyclibrary and in the correct order (header files are parsed in the order in which they are provided) ? If you pass the file containing the definition of MY_BITFIELD in second position it could explain why things fail.

**Comment by MatthieuDartiailh** [comment]
Closing for lack of feedback feel free to reopen if necessary.
