### ISSUE TITLE
Wrong order of sizes in multidimensional arrays

### ISSUE THREAD

**Issue by ocroquette** [MatthieuDartiailh/pyclibrary#44]
I have the following C code:

```
typedef struct {
    char array[10][20];
} StructWith2dArray;

__stdcall void FillStructWith2dArray(StructWith2dArray* s) {
    for(unsigned int i = 0; i < 10; i++) {
        sprintf(s->array[i], "String %d", i);
    }
}
```

And the following Python code using pyclibrary:

```
s = example_dll.StructWith2dArray()
example_dll.FillStructWith2dArray(ctypes.pointer(s))
for i in range(10):
    print("  {}: {}".format(i, char_array_to_string(s.array[i])))
```

The output in the following:
```
  0: String 0
  1:
  2: String 1
  3:
  4: String 2
  5:
  6: String 3
  7:
  8: String 4
  9:
```

So basically, instead of getting from pyclibrary an array of 10 strings with 20 char each, I get an array of 20 strings with 10 characters each.

Here is the corresponding output of print_all():
```
{   ...
    'anon_struct1': Struct(('array', Type('char', [10], [20]), None))}
```

 I am doing something wrong?
If this is a bug, is there any easy workaround?

**Comment by MatthieuDartiailh** [comment]
Honestly I am not sure what is going and I have not used pyclibrary in a long time. The first thing I would try would be to manually write a ctypes wrapper for this function and try to get it to behave properly. If you get that to work it will be easier to compare to what pyclibrary generate.
If you manage to do please post the code and I will have another look.

**Comment by ocroquette** [comment]
Thanks for the quick reply. Here is the equivalent ctypes code, which works as expected:

```
class StructWith2dArray(ctypes.Structure):
    _fields_ = [
     ("array", (ctypes.c_char * 20) * 10),
    ]
s = StructWith2dArray()
example_dll.FillStructWith2dArray(ctypes.pointer(s))
for i in range(10):
    print("  {}: {}".format(i, char_array_to_string(s.array[i])))
```

Here is the output:
```
  0: String 0
  1: String 1
  2: String 2
  3: String 3
  4: String 4
  5: String 5
  6: String 6
  7: String 7
  8: String 8
  9: String 9
```

I tried some hacks in the pyclibrary source code but was not successful.

**Comment by MatthieuDartiailh** [comment]
Thanks ! I will try to have a look but it may not happen before Wednesday next week. Do not hesitate to ping me if I do not come back to you.

**Comment by ocroquette** [comment]
Thank you! Here is the code for the function ```char_array_to_string``` by the way:

```
def char_array_to_string(ca):
    """Convert a C char array to a Python string"""
    return ctypes.cast(ca, ctypes.c_char_p).value.decode()
```

**Comment by MatthieuDartiailh** [comment]
Having a quick look the issue is likely related to https://github.com/MatthieuDartiailh/pyclibrary/blob/master/pyclibrary/backends/ctypes.py#L194 in which we go through modifiers in order. The issue is that I don't really see a way to defer that evaluation. However we do iterate on the list so we may be able to join lists in the parser and then iterate in reverse order. I will keep looking.

**Comment by ocroquette** [comment]
Thank you for investigating.

In my case, I know how the array must be. Is there any way to "hot fix" the data structures of pyclibrary  after the header files have been parsed? That would be a workaround of course, but it would allow to work with the array in the meantime.

**Comment by MatthieuDartiailh** [comment]
I have a fix in https://github.com/MatthieuDartiailh/pyclibrary/pull/45 but I had not time to test it. If you can have a look that would be great.

**Comment by ocroquette** [comment]
It doesn't work unfortunately, this is then the output:
```
  0: String 0
  1: 
  2: 
  3: 
  4: 
  5: 
  6: 
  7: 
  8: 
  9: 
```
Here is the full code I use:

[Example.zip](https://github.com/MatthieuDartiailh/pyclibrary/files/4942359/Example.zip)

**Comment by MatthieuDartiailh** [comment]
Thanks for the reproducer. I do not have access to a windows machine right now but I believe I found the source of the issue, fixed it and added a minimal test to avoid future regression.

 If you can test that would be great, otherwise I will test later when I get access to a windows machine.

**Comment by ocroquette** [comment]
ba675bf7e015c78102df9bda903d4e839ac2d880 solves the issue, thank you !

**Comment by ocroquette** [comment]
Sorry I didn't mean to close, I guess you will do that once the fix is merged to master. Reopening.

**Comment by MatthieuDartiailh** [comment]
Happy I got it right this time ! I will try to release sometimes next week.

**Comment by ocroquette** [comment]
Excellent, thank you very much!

**Comment by MatthieuDartiailh** [comment]
New release is available on PyPI
