### ISSUE TITLE
Provide type_qualifiers to backend

### ISSUE THREAD

**Issue by mrh1997** [MatthieuDartiailh/pyclibrary#5]
Currently type_qualifiers (i.e. the "const" in ```const int * a```) are not exposed via the CParser API. But this kind of information can be important for generating C-wrappers (I.e. in our case we need to create a RPC mechanism from PC to an embedded devices, which uses a C compiler with a couple of custom type_qualifiers for giving the developer access to the uC features like different memory types).

Unfortunately it is not too easy to add this feature to the library without breaking compatibility with the existing interface. The reason is that the API is representing a C type in python tuples (I.e. ```('int', '**', [2], [4])``` for the C definition ```const int * * [2][4]```).

My proposal is, to add a class, that derives from 'tuple' and can store additional field names (like type qualifiers( without breaking compatibility:

```python
class AnnotatedType(tuple):
    def __init__(self, rawTypeTuple, **additionalParams):
        super(AnnotatedType, self).__init__(rawTypeTuple)
        for name, val in additionalParams.iteritems():
             setattr(self, name, val)

const_int = AnnotatedType('int', type_qualifiers=["const"])
assert const_int == "int"
assert const_int.type_qualifiers == ["const"]
```

Please let me know if you like this solution or if you have better ideas. If you agree with my proposal, I would provide a patch.

**Comment by MatthieuDartiailh** [comment]
This makes sense to me. For the time being those informations are simply being suppressed by the parser, you will have to dig a bit in the parser logic to fix this (you should look at lines : 808 (function build_parser), 1449.
I am fine with your proposed implementation, simply takes care that you need to override the \_\_new\_\_ method of tuple (see http://stackoverflow.com/questions/1565374/subclassing-python-tuple-with-multiple-init-arguments). For consistency I think it would make sense to use the new class everywhere. Furthermore as we will have a lot of those objects around it would makes sense to slot them. And finally one last point the code should be python 2/3 compatible so don't use iteritems but items (as we are working on small dictionaries the performance difference is minimal).
I think that new class should be defined in the utils.py module and note that all code should follow PEP8 specifications.

If you have any other questions do not hesitate.

**Comment by mrh1997** [comment]
I agree in all items with you. Only the "single-class-for-everywhere" approch is worth discussing it.

If we use a single tuple-derived class **everywhere** we cannot work with slots, since every kind of parser object has different attributes (I.e. a *type* object has 'type_qualifiers', while a *fnmacro* object has a 'replace_text').

I think we have two possibilties (both derives from tuple for compatibility):

| AnnotatedTuple | TypeObject / MacroObject / ... |
| -------------------- | -------------- |
| a single object for all purposes | a specialized object for every purpose |
| attributes are added dynamicially (dependend on requirement) | a fix set of attributes is provided as slots |
| located at utils (since it is usable independently of c_parser.py) | located at cparser (since it makes only sence with CParser()) |

I strongly prefer the second approach (specialized objects), since this would be more idiomatic for python in my opinion.

I would even propose to add a ```__repr__()``` method, that displays the actual constructor of the object and not a tuple any more. This would increase readability of ```parser.print_all()```. Especially if one is working the first time with pyclibrary.

**Comment by MatthieuDartiailh** [comment]
Actually my point was to use it everywhere types are concerned not for every object returned by the parser, but I like a lot your idea of specialized object to represent the different result of the parser. If you have time enough to invest in the solution you are proposing I am all for it. As it seems pretty easy to decouple the updates needed for each type of object, it would probably be better to deal with them one (or two) at a time to make reviewing easier and hence faster. Furthermore it would allow me to jump in at some point if I can find time to do so.
