### ISSUE TITLE
Switch to a more orthogonal "pointer of pointer type" parser representation

### ISSUE THREAD

**Issue by mrh1997** [MatthieuDartiailh/pyclibrary#6]
Currently the type of the C variable-def ```int * * a;``` is represented in c_parser as ```('int', '**')```. I propose to change this to ```('int', '*', '*')``` for the following reasons:
* it is less complicated to process the type object since it is possible then to iterate the pointer/array parts a type with a single ```for ptrArr in typeTuple[1:]: ...``` (currently you have to work with a nested for loop, if a '*...' ptrArr is detected).
* When introducing issue #5 a simple way to refer to the ptr/array level needed, to refer them from a attached type_qualifier (every level can have its own type qualifiers; By the way: this is currently a bug, since ```int * const * a``` is not supported yet, although valid C code and not the same as ```int const * * a```; I will fix this...)
* it is more intuitive, since arrays are represented this way, too (```int a[1][2]``` is represented as ```('int', [1], [2])```, not as ```('int', [1,2])```)
* it is more orthogonal, since ```int *(*a);``` is represented as ```('int', '*', '*')```, too

The last reason is also the reason why we will not break compatibility with existing applications (they have to have the ability to process these kind of split pointer strings already, otherwise they could not process ```int *(*a);```)

Please let me know if you go OK with my proposal or if you want me not to provide a patch.

**Comment by MatthieuDartiailh** [comment]
I think this makes perfect sense. We will just have to be careful about the library but as you said it should make things simpler. So that PR are easier to review, I would like to keep them small.I if you could do first a PR for this issue and later one for #5 it would be perfect. I will try to review them as quickly as possible.

**Comment by mrh1997** [comment]
Arrays as arrays suffer the same problem as pointer of pointers:
```python
a = Type('int', [1, 2])   # int a[1][2];
b = Type('int', [1], [2]) # int (b[1])[2];
```
I'll fix this, too (same motivation as splitting '**' into '*', '*'; Should be no compatibility problem)

**Comment by mrh1997** [comment]
By Merging #9, This issue is solved
