### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by AlanRosenthal** [MatthieuDartiailh/pyclibrary#60]
Hi! Big fan.

Looks like there's been 2 years and almost 200 commits since the last release. Any plans for a new release?

Thanks!

**Comment by MatthieuDartiailh** [comment]
Sadly this project tends to be at the bottom of my open source priorities and does not get much attention. I will do my best to do a release by the end of the month. Do not hesitate to ping me if you do not see anything coming.
