### ISSUE TITLE
Support pyparsing>=3 too

### ISSUE THREAD

**Issue by JasperCraeghs** [MatthieuDartiailh/pyclibrary#61]
I'm building a Docker image that includes pyclibrary and another package that requires [pyparsing>=3.*](https://github.com/pyparsing/pyparsing/releases). Please add support for it or mark it as supported if it already is. I have not tested this.

**Comment by MatthieuDartiailh** [comment]
I do not have the bandwidth to address this issue. I would review a PR but I cannot do more.
